### ISSUE TITLE
Feature request: Force polling watcher

### ISSUE THREAD

**Issue by TBBle** [samuelcolvin/watchfiles#134]
I am developing a small tool using this code. to run in a container on Linux that watches a mounted volume.

However, I am developing this on a Windows machine, and a folder mounted from Windows into WSL (where the Docker daemon and its containers are hosted) does not support inotify; see https://github.com/microsoft/WSL/issues/4739

I am _guessing_ that the pollwatcher would work correctly here, since I confirmed the relevant file _is_ present in the container, there's just no inotify event. https://github.com/gorakhargosh/watchdog/issues/877 is the same use-case, and the fix there was switching from the inotify implementation to a directory-polling implementation. That project also notes [that you must force polling for CIFS filesystems](https://github.com/gorakhargosh/watchdog#about-using-watchdog-with-cifs) but not which platform/watcher implementation CIFS doesn't work with. (Perhaps it's all of them?) So this might also benefit any users trying to watch CIFS filesystems.

Unless I've overlooked something, I don't see an existing way to do the same override here.

In the meantime, I'm just testing with directories mounted from the WSL drive rather than the Windows drive, so this isn't a blocking issue for me right now.

Perhaps the APIs that take a `debug` flag for Rust could also take a `force_polling` flag or something like that to pass into RustNotify's `py_new`?

**Comment by samuelcolvin** [comment]
Happy to accept a pr if you can get `force_polling` to work. 

No idea how hard it would be.

**Comment by samuelcolvin** [comment]
Should be done in #135, just needs some tests.

Can you let me know if that fixes your problem?

**Comment by TBBle** [comment]
I had a quick burl at getting a build, but it's failing on CI (test run fails after wheel build) so I didn't get a wheel to test. I haven't looked into why yet, I'll have another look on Monday.

**Comment by samuelcolvin** [comment]
Tests are fine, just we don't build the binaries on pr commits because it takes an hour.

You'll need to compile the extension yourself, the error is because you haven't compiled the extension.

Or I could release a bit more CO2 AND and build binaries on all commits - it would help in a few places.

**Comment by TBBle** [comment]
The error came from the project's CI script. I forked your PR and added a commit to [run the builds on my branch](https://github.com/TBBle/watchfiles/actions/runs/2249379525), and that's where it failed.

**Comment by samuelcolvin** [comment]
Yup, I know what that is, I'll fix it.

**Comment by samuelcolvin** [comment]
Should be fixed on the PR.

**Comment by TBBle** [comment]
I grabbed the `watchfiles-0.0.dev0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64` from [the last run of #135](https://github.com/samuelcolvin/watchfiles/actions/runs/2253781430) and tried it with `force_polling=True`, and it indeed picks up changes from the Windows folder mounted into the Linux container. (Without `force_polling=True`, it still does not see the changes, as expected).

So thank you, my limited testing says the issue is fixed by #135.

**Comment by samuelcolvin** [comment]
Any volunteers for https://github.com/samuelcolvin/watchfiles/issues/187?
